[options]
[textrules]
style_semicolon = true
style_textwidth = true

[syntaxrules]
case_default = true
eventlist_or = true
explicit_if_else = true
keyword_forbidden_always = true
keyword_forbidden_wire_reg = true
loop_variable_declaration = true
multiline_for_begin = true
multiline_if_begin = true
uppercamelcase_module = true

